### ISSUE TITLE
Execution failed with error wrong number of arguments (4 for 0)

### ISSUE THREAD

**Issue by darkleaf** [dtaniwaki/sidekiq-merger#5] opened 2017-07-25 15:42 UTC
gem 'sidekiq-merger', github: "dtaniwaki/sidekiq-merger"
gem 'sidekiq', '4.2.9'

`Execution failed with error wrong number of arguments (4 for 0)`

Problem in https://github.com/dtaniwaki/sidekiq-merger/blob/master/lib/sidekiq/merger/middleware.rb#L19

```
sidekiq_1  | /home/web/bundle/bundler/gems/sidekiq-merger-419f4e971a91/lib/sidekiq/merger/merge.rb:76:in `flush'
sidekiq_1  | /home/web/bundle/bundler/gems/sidekiq-merger-419f4e971a91/lib/sidekiq/merger/flusher.rb:12:in `each'
sidekiq_1  | /home/web/bundle/bundler/gems/sidekiq-merger-419f4e971a91/lib/sidekiq/merger/flusher.rb:12:in `flush'
sidekiq_1  | /home/web/bundle/bundler/gems/sidekiq-merger-419f4e971a91/lib/sidekiq/merger.rb:21:in `block in create_task'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/timer_task.rb:309:in `execute_task'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/scheduled_task.rb:285:in `process_task'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/timer_set.rb:168:in `block (2 levels) in process_tasks'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
sidekiq_1  | /home/web/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by dtaniwaki** [comment] 2017-10-12 11:40
I can't reproduce your issue in my environment. Could you tell me more information such as a sample of your `sidekiq_options` and `perform` action?

**Comment by darkleaf** [comment] 2017-10-12 12:11
It's been so late. 
I wrote own daemon for grouping jobs.
Currently I don't need this gem. Sorry.

May be another users will send more information.

**Comment by dtaniwaki** [comment] 2017-10-12 13:05
Thank you for your reply. I’m closing it.

**Closed by dtaniwaki** 2017-10-12 13:05 UTC
